### ISSUE TITLE
Triggers - Blocking Cityworks Auto-Close - Stop Write to Audit Log

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#16]
The trigger was correctly updated to block the auto-closure of SRs rather than reversing it.  The updates has been confirmed to prevent the SR from getting closed in the CSR system.

There is one issue remaining, however.  There is an "audit log" in Cityworks that shows each change to the SR and who changed it when.  This is still capturing the Closed By, Closed Date, and Status change to CLOSED, even though the SR is never actually closed.  The system must write this info to the audit log (CWMETADATA) prior to the SR.

This can be stopped or deleted after writing, as long as it is not there, like such:
![image](https://cloud.githubusercontent.com/assets/5805454/10165982/edd4ecf0-668f-11e5-9f61-532b261e1dde.png)

**Comment by gerrykelly** [comment]
I think this should work:  I modified the instead of update trigger on REQUEST so that when the set-status to CLOSED is preempted, those related three records that were inserted into CWMETADATA get deleted by the following new SQL...

  delete from [azteca].[CWMETADATA] where [OBJECTID] in (
SELECT max([OBJECTID]) FROM [azteca].[CWMETADATA] 
 where [TABLENAME] = 'REQUEST' and [FIELDNAME] = 'STATUS' and newvalue = 'CLOSED' and CWID =  @reqID
 group by [OBJECTID]
 union
SELECT max([OBJECTID]) FROM [azteca].[CWMETADATA] 
where [TABLENAME] = 'REQUEST' and [FIELDNAME] = 'DATETIMECLOSED'  and CWID =  @reqID
 group by [OBJECTID]
 union
SELECT max([OBJECTID]) FROM [azteca].[CWMETADATA] 
 where [TABLENAME] = 'REQUEST' and [FIELDNAME] = 'CLOSEDBY'  and CWID =  @reqID
 group by [OBJECTID]);

**Comment by JMurk** [comment]
Hmm, seem like it should work, but it is still appearing in CW this morning:

![image](https://cloud.githubusercontent.com/assets/5805454/10194586/92d6e330-6757-11e5-8986-e0bf40b3b1c7.png)

**Comment by JMurk** [comment]
The records are not being deleted from the table, but I have verified that the code works in a standalone manner. It appears that it is not being fired within the trigger:

IF  @cntNotClosed > 0  and @newStatus = 'CLOSED' and  @oldStatus <> 'CLOSED' begin

**Comment by JMurk** [comment]
Confirmed complete.
