### ISSUE TITLE
CityWorks 2014 - Service Request - Caller Information Look Up doesn't work

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#3]
When entering caller information the Caller Lookup function fails to find callers that I've entered in previous service requests.  I created a work order for caller Joe Blow.  Then I created a second work order.  Joe Blow was not found.

![callerlookup](https://cloud.githubusercontent.com/assets/9657650/4978761/2d1046b8-68f2-11e4-89ea-184a2745d1ad.png)

**Comment by JMurk** [comment]
I have confirmed that the caller look-up function searches the customer ACCOUNT table.  These accounts are setup on the back-end.  Currently the table is empty, which is why the search does not return anything.

When a caller is entered for an SR, the system does not save an account for them.

Also, Baltimore City doesn't create SRs directly in Cityworks, so this won't be a problem.
